version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/web
    owner: ec2-user
    group: ec2-user
    mode: "766"
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
#   BeforeInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
#   ValidateService:
#     - location: scripts/basic_health_check.sh